server:
  port: 8090
  context-path: /girl

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/malei
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true

